# Generated by Django 5.1.3 on 2024-11-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(default='Course')),
                ('name', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='lectures/videos/')),
                ('ebook', models.FileField(upload_to='lectures/notes/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lectures/images/')),
            ],
        ),
    ]
